CREATE DATABASE IF NOT EXISTS espinozasa;
USE espinozasa;
CREATE TABLE USUARIOS
(
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    USER VARCHAR(25) NOT NULL,
    CONTRASENA VARCHAR(33) NOT NULL
);

INSERT INTO USUARIOS (USER,CONTRASENA) VALUES ('valeria','2048d4fc09d84f3e39c7ddfe6196c0e5');