CREATE DATABASE IF NOT EXISTS espinozasa;
USE espinozasa;
CREATE TABLE USUARIOS
(
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    USER CHAR(25) NOT NULL,
    CONTRASENA CHAR(25) NOT NULL
);
INSERT INTO USUARIOS
(USER,CONTRASENA)
VALUES 
('valeria','espinoza');